spring:
    application:
        name: Challenge
    datasource:
        url: jdbc:postgresql://localhost:5433/challenge
        username: postgres
        password: postgres
    jpa:
        hibernate.ddl-auto: update
        properties.hibernate:
            jdbc.lob.non_contextual_creation: true
            dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8080
